# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          http://aj-adl.github.io/poole/
author:
  name:           Alex Bishop
  url:            https://twitter.com/aj_adl
  email:          alex (at) bshpdigital.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/aj-adl/poole
